#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$container = require __DIR__ . '/bootstrap.php';

exit((new \App\Application($container))->handleCli($argv));
